### ISSUE TITLE
About message and update function

### ISSUE THREAD

**Issue by jermainewang** [zzhang-cn/dgl#8]
I'm thinking about how to make the API cleaner. Basically, we only have two types of computations:
* **Computation on edge**. It takes the states of the src and dst nodes, and the old states of the edge and returns the new states of the edges. The signature can be summarized as:
  `(node_states, node_states, edge_states) -> edge_states`
* **Computation on node**. It takes the states of the in-coming edges and the old node states to compute the new node states. The signature can be summarized as:
  `(list[edge_states], node_states) -> node_states`

In networkx, all node and edge states are dictionaries (you can use `type(g.nodes[node])` to verify this).

A message function can be viewed as a special edge computation as follows:
```python
def edge_func(src_node_states, dst_node_states, edge_states):
  msg = ...  # compute message
  new_edge_states = edge_states
  new_edge_states['msg'] = msg
  return new_edge_states
```
Because this pattern is so common, we can let user only returns the `msg` and handle the edge state update by ourselves:
```python
def mfunc(node_states, edge_states):
  #User-defined
  msg = ... # compute message
  return msg
def mfunc_wrapper(src_node_states, dst_node_states, edge_states):
  #System wrapper
  new_edge_states = edge_states
  new_edge_states['msg'] = mfunc(src_node_states, edge_states)
  return new_edge_states
```

Similarly, we can wrap the update function as node function as well:
```python
def ufunc(msgs, edge_states, node_states):
  #User-defined
  new_node_states = ...  # compute new node state
  return new_node_states
def ufunc_wrapper(edge_states, node_states):
  #System wrapper
  msgs = [es['msg'] for es in edge_states]
  new_node_states = ufunc(msgs, edge_states, node_states)
  return new_node_states
```

I want to know your opinions about this implementation. Using this idea, we might have two basic APIs: `register_edge_func` and `register_node_func`. And have `register_message_func` and `register_update_func` be two APIs that simply wrap the above two.

**Comment by zzhang-cn** [comment]
Do you mean we expose `register_edge_func` to user and reserve `register_message_func` for system use?

**Comment by jermainewang** [comment]
I'm thinking about having both, but `register_message_func` is implemented using `register_edge_func`, so in the system side, we still only see two kinds of computation.

If the user's model is like GCN style:
```
# on edge u->v
msg = f1(u)
v' = f2(list[msg], v)
```
, then he only needs to `regsiter_message_func(f1)` and `register_update_func(f2)`.

If the user's model is like:
```
# on edge u->v
msg = f1(u, e_uv)
v' = f2(list[msg], list[e_uv], v)
e_uv' = f3(u, v, e_uv)
```
, then he needs to `register_message_func(f1)`, `register_update_func(f2)` and `register_edge_func(f3)`.

**Comment by zzhang-cn** [comment]
in the second case, i would do `msg = zip(f1(u, e_uv), e_uv))`, so still only two APIs.

**Comment by zzhang-cn** [comment]
Is this a problem to solve urgently or we can table for later?

**Comment by jermainewang** [comment]
As discussed in the meeting, let's try to implement the Molecular GCN model (with both message function and learnable edge features) before drawing conclusions. Close the issue at the moment.
